openstack-k8s-operators/lib-common

.travis.yml
ci_scripts/travis.golint.sh
ci_scripts/travis.govet.sh
pkg/util/hosts.go
pkg/util/marshaller.go
pkg/util/object_util.go
pkg/util/template_util.go

Simple style type check jobs for the project with place for
further stages such as unit tests.

Initial travis setup that supports lint and vet

---

pkg/common/deployment.go
pkg/common/secret.go

* Add method to get deployment object
* Add GetDataFromSecret and update GetSecret/s to use helper

Update deployment + adds GetDataFromSecret and update GetSecret/s to use helper

---

pkg/common/pvc.go
pkg/common/pvc_types.go

Common PVC object

---

modules/common/endpoint/endpoint.go

New approach to `ExposeEndpoints` func that allows for customization of the URL generated for Keystone

Allow some customization of endpoint URL format

---

modules/common/condition/funcs.go
modules/common/condition/funcs_test.go
modules/database/go.mod
modules/openstack/go.mod

Helper func to check if a condition represents an error. IsError is true if the condition is
a) not nil,
b) `status=False` and
c) `condition.Reason == condition.ErrorReason`
Otherwise it returns False if the condition is not True or if the condition does not exist (is nil).

Add IsError(c *Condition) to check if a condition has ErrorReason

---

modules/database/go.mod
modules/openstack/go.mod

updates the two modules to remove the not valid version v0.0.0-00010101000000-000000000000

Update common and database module to remove not valid version

---

modules/common/endpoint/endpoint.go

* Include the TCP port number in the endpoint
* Use the service name as the hostname for internal endpoints, since that will work for openstack pod -> pod requests
* Get some parse validation but punt on ever parsing the path component because of %(project_id)s placeholder
* Special-case port 80 with http
Example endpoints created with this:
- interface: public url: http://ironic-public-openstack.apps.dell-opti.stevebaker.org:6385/v1/82b04483205f4c499826f51ec532c89f
- interface: internal url: http://ironic-internal:6385/v1/82b04483205f4c499826f51ec532c89f
Handling https remains a TODO

Rework endpoint URL building

---

modules/common/job/job.go

With #78 lib-common uses TTL on Jobs to clean them up and to support PreserveJob the TTL can be change on a Job even after it is finished. However #78 has a bug as it tries to CreateOrPatch the Job _after_ it is deleted but with an empty Job definition. This fails with
>   "error": "an empty namespace may not be set during creation"
This patch makes sure that lib-common only tries to update the TTL if the Job exists.

Only try to update TTL on an existing Job

---

modules/test/helpers/configmap.go

Signed-off-by: Bogdan Dobrelya <bogdando@yahoo.com>

Return by pointer for consistency

---

modules/common/statefulset/statefulset.go

Needed to make use of VolumeClaimTemplates properly.

Use VolumeClaimTemplates if set

---

modules/database/funcs.go

continue from : https://github.com/openstack-k8s-operators/lib-common/pull/54

add database finalizers add and remove logic

---

LICENSE

http://www.apache.org/licenses/LICENSE-2.0
Signed-off-by: Fabricio Aguiar <fabricio.aguiar@gmail.com>

Add Apache License  Version 2.0

---

.github/workflows/codeql.yml

Add CodeQL workflow to find security vulnerabilities

---

modules/common/service/service.go

Adds functions to set a Service with name in namespace and one to get a ServicePort with its name from the service.

Add GetServiceWithName and GetServicesPortDetails

---

modules/common/pod/pod.go

Adds pod pkg with func to get a podList from a namespace matching a label selector.

Add pod pkg

---

modules/common/condition/funcs.go
modules/common/condition/funcs_test.go

We would need to remove a condition at times from the conditions slice. This adds the new helper function for it.

Add remove function to conditions

---

modules/common/endpoint/endpoint.go

We missed this when switched to time.Duration for NewService and NewRoute

Use time.Duration in ExposeEndpoints

---

modules/ansible/go.mod
modules/ansible/go.sum
modules/ansible/inventory.go
modules/ansible/inventory_test.go

1 - https://github.com/openstack-k8s-operators/lib-common/pull/180
2 - https://github.com/openstack-k8s-operators/dataplane-operator/pull/39
3 - https://github.com/openstack-k8s-operators/openstack-ansibleee-operator/pull/89

Move ansible module from AEE

---

modules/common/pod/pod.go

As memcached is likely to be used by multiple services, this change adds some common functions likely necessary to interact with the memcached CR. Adding these to lib-common will reduce the overhead of updating multiple service operators if the interface with memcached and it's associated CR are to change in the future.

Add common function to lookup Headless service pods

---

modules/common/util/env.go
modules/common/util/env_test.go

Currently desired for getting env var for defaults used with webhooks.

Util func for getting OS env vars

---

modules/test/helpers/deployment.go
modules/test/helpers/statefulset.go

In the effort of adding `envTest` across the storage operators, we've realized that many operators
should take advantage of a lot of functions if defined in `lib-common`.
This patch moves the common functions (used in also in [1]) to the helpers module.
[1] https://github.com/openstack-k8s-operators/manila-operator/pull/67/

Simulate Deployment and StatefulSet Ready with Pods

---

modules/openstack/limits.go

This PR will add support to Update, Delete, List and Get particular registered limit.

Add CRUD support for registered limits

---

Makefile

Just like in all of our other repos.

Adding makefile help target

---

modules/openstack/openstack.go

Allows to pass in TLSConfig settings the the openstackclient for register e.g. endpoints.
The config can be a list of CACert's, Insecure parameter and client cert/key.
Jira: OSP-26299
Jira: OSP-26845

[TLS] Gophercloud client to support TLS settings

---

modules/certmanager/issuer.go

[TLS] add RootCAIssuerInternalLabel

---

modules/common/tls/tls.go
modules/common/tls/tls_test.go

[TLS] Mount tls cert/key + ca-bundle into /etc

---

modules/common/tls/tls.go

[TLS] add CABundleLabel

---

modules/certmanager/certificate.go

Add support for usages and ip address SANs in the cert requests

Modify EnsureCert to support certs with IPs and usages

---

modules/certmanager/issuer.go
modules/certmanager/test/functional/certmanager_test.go

[certmanager] Adds func GetIssuerByName() to get an issuer by name

---

modules/common/secret/secret.go

Reconsile inside the passed in callback MutateFn to properly update a secret.

Fix secret.CreateOrPatchSecret to properly patch secret

---

modules/test/crd.go
modules/test/crd_test.go

This change modifes how we calculate the path for a module
to allow github usernames with any case to funciton.
the previous code only work for all lowercase usernames
the usernames in github are canonically cases senseitve even
though any case is accpeted in the url.
The path on disk used by go will however be lowercase.
This change makes our code have the same behvior.

Normalize module/crd path

---

modules/certmanager/certificate.go

Returns an NotFound error if <1 or >1 service found using the selector.

[certmanager] EnsureCertForServiceWithSelector return NotFound error

---

modules/common/test/helpers/pod.go

Anticipated to be needed in work to address https://issues.redhat.com/browse/OSPRH-5019.

Test helper func for simulating pod running phase

---

modules/common/test/helpers/pod.go

More additions anticipated to be needed in work to address https://issues.redhat.com/browse/OSPRH-5019.

Test helper func for simulating pod ready state

---

modules/common/cronjob/cronjob.go

The original CronJob fix was incomplete

Follow up for 7b9e9510924

---

modules/certmanager/test/functional/certmanager_test.go

cover tests where no issuer is found using label and multiple issuers got returned by the passed in label.

[certmanager] enhance GetIssuerByLabels tests

---

modules/certmanager/issuer.go

Add OvnDb root CA issuer label

---

modules/certmanager/certificate.go

[certmanager] add RenewBefore to CertRequest

---

modules/common/condition/conditions.go

[condition] add redis condition

---

modules/common/condition/conditions.go

This reverts commit f5727c635c87677db2f6de7a3e91f05c7b06209f.

Revert "[condition] add redis condition"

---

modules/common/test/helpers/deployment.go

Add method that will simulate any number of replicas ready

Add SimulateDeploymentAnyNumberReplicaReady

---

modules/common/test/helpers/deployment.go

This patch modifies the SimulateDeploymentReadyWithPods test function to not add network annotations when an empty map is passed to it.
This patch is required because we are removing networkAttachments for ovnNorthd (it's not needed, see [0]) and tests needs to be updated.
[0] https://github.com/openstack-k8s-operators/ovn-operator/pull/269

Do not add network annotations in SimulateDeploymentReadyWithPods

---

modules/common/job/job.go

https://github.com/kubernetes/kubernetes/blob/74d578485dcf076fdbbf3c09e1b0ae43c52c19d7/pkg/apis/batch/types.go#L360

Fix HasReachedLimit when BackoffLimit is nil

---

modules/common/serviceaccount/serviceaccount.go

Related: https://issues.redhat.com/browse/OSPRH-8379

Fix merging ServiceAccount annotations

---

modules/common/serviceaccount/serviceaccount.go

Related: https://issues.redhat.com/browse/OSPRH-8379
(cherry picked from commit 8c7f426d594a6a5274580e6f5f1ee3be5f6330c0)

[18.0.0-proposed] Fix merging ServiceAccount annotations

---

modules/common/daemonset/daemonset.go

Needed-by: https://github.com/openstack-k8s-operators/ovn-operator/pull/337
Related: OSPRH-7463

[daemonset] Make get method public

---

modules/storage/storage.go

A few helpers to get the new storage and extramounts structs working with openstack-operator

storage: Add new ToCoreVolume and ProjectVolumeSource
