pkg/util/ssh.go
Adds [1] from nova-operator to lib-common. Tests to follow.
[1] https://github.com/openstack-k8s-operators/nova-operator/blob/master/pkg/util/ssh.go
=> Move ssh lib from nova-operator to lib-common

pkg/common/const.go
Moves AppSelector, InputHashName and DebugCommend to shared const
in lib-common to be used by all operators, instead of specify it
in the operator itself.
=> Add shared const used by operators

pkg/helper/helper.go
Add the gkv.Kind as generic finalzer to the helper.
This removes the req to add a const per CRD as finalizer
and can be added to objects wherever needed and the
helper is available.
=> Add gkv.Kind as finalizer to helper

pkg/database/funcs.go
Database.setDatabaseHostname() call assumed that
common.GetServicesListWithLabel returns an error if no service is found.
However that call returns an empty list instead. This could lead to
panic in setDatabaseHostname when tried to index an empty list.
This patch extend the error guard condition to cover the empty list
case.
Closes openstack-k8s-operators#27
=> Check length of the serviceList before indexing

pkg/openstack/role.go, pkg/openstack/service.go, pkg/openstack/user.go
GetUser, GetService and GetRole returned an error if the
specified resource with the name could not be found, which
is still ok when checked if it exists or need to be created.
In that case return nil and the caller need to check on that
and acts appropriate.
=> Don't return an error if resource is not found in keystone

modules/openstack/user.go
If an openstack user does not already exist when attempting to create the user, do not treat it as an error
=> Fix OS user create/delete when not found

.gitignore, Makefile
- Instead of rely on go.work file, just loop through all module directories in /modules for all the check targets.
- Add make target for go.work and to .gitignore
=> Loop through all module dirs for checks

.gitignore, Makefile, modules/common/endpoint/endpoint.go
* ignore vendor dirs if created in modules folders
* Exit if there is an error found in check runs looping over folders
* Fix EndpointData lint error
=> Exit when go checks detect error

modules/common/condition/funcs.go, modules/common/condition/funcs_test.go
CreateList is a useful func to create a conditions type list when
e.g. pass to the `condition.Init(cl *Conditions)` func, like e.g.
```
cl := condition.CreateList(
condition.UnknownCondition(condition.InputReadyCondition,...),  
condition.UnknownCondition(condition.DBReadyCondition,...),
condition.UnknownCondition(condition.DBSyncReadyCondition,...))
instance.Status.Conditions.Init(&cl)
```
Therefore to make it obvious move it from funcs_test.go to funcs.go
and rename it to `CreateList(...)`.
=> Move conditionList from test to CreateList

modules/common/condition/conditions.go
Adds messages used when the conditon gets initialized at the
start of reconciliation.
This could then look like:
```
cl := condition.CreateList(
condition.UnknownCondition(keystonev1.KeystoneAPIReadyCondition, condition.InitReason, keystonev1.KeystoneAPIReadyInitMessage),
condition.UnknownCondition(keystonev1.AdminServiceClientReadyCondition, condition.InitReason, keystonev1.AdminServiceClientReadyInitMessage),
condition.UnknownCondition(keystonev1.KeystoneServiceOSServiceReadyCondition, condition.InitReason, keystonev1.KeystoneServiceOSServiceReadyInitMessage),
condition.UnknownCondition(keystonev1.KeystoneServiceOSEndpointsReadyCondition, condition.InitReason, keystonev1.KeystoneServiceOSEndpointsReadyInitMessage),
condition.UnknownCondition(keystonev1.KeystoneServiceOSUserReadyCondition …
```
=> Add condition init messages

modules/common/condition/funcs.go, modules/common/condition/funcs_test.go, modules/common/condition/types.go
*   Add Mirror(t Type) to reflect client object conditions state
Mirror(t) mirrors Status, Message, Reason and Severity from the
latest condition of a sorted conditionGroup list into a target
condition of type t.
The conditionGroup entries are split by Status with the order
False, True, Unknown. If Status=False its again split into Severity
with the order Error, Warning, Info.
If the overall ReadyConditon is true, it is expected that this is
the actual state and no other groups need to be checked.
To e.g. mirror the keystoneservice object condition it only required
to use:
~~~
c := ksSvc.GetConditions().Mirror(condition.KeystoneServiceReadyCondition)
if c != nil {
instance.Status.Conditions.Set(c)
}
~~~
Example Depends-On: https://github.com/openstack-k8s-operators/keystone-operator/pull/8 …
=> Add Mirror functionality to sync lower level object condition state into the upper level

modules/common/statefulset/statefulset.go
Adds a missing refresh of the lib-common's `StatefulSet` object's underlying `appsv1.StatefulSet` object after it is created/updated
=> Refresh statefulset object on create/update

modules/common/condition/funcs.go, modules/common/condition/funcs_test.go
GetHigherPrioCondition validates the priority of two conditions based on groupOrder(c) and returns the one which has precedence of the other.
If one of them is nil, the non nil get returned.
=> Add GetHigherPrioCondition to compare prio of two conditions

modules/database/funcs.go
When trying to deploy Keystone without MariaDB being already deployed,
the Keystone operator would segfault as follows [1]. The segfault is
now fixed by not trying to dereference the d.database pointer when the
database wasn't found.
[1]
```
1.6606757169899645e+09  INFO    controllers.KeystoneAPI Reconciling Service
1.6606757170078285e+09  INFO    controllers.KeystoneAPI Input maps hash input - n58bh5f6h59ch599hf5hfchc5h558h9chdh598h66bh8hch669h5h595hf5h676h5f7h85h545hfch66bh655h67h569h556h56hdbh699h546q
1.660675717007914e+09   INFO    controllers.KeystoneAPI Reconciling Service init
1.6606757170226123e+09  INFO    Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference        {"controller": "keystoneapi", "controllerGroup": …
```
=> Prevent segfault when DB instance is not found

modules/common/job/job.go
Need to check the Succeeded could before checking the Failed count when determining the job status.
=> [OSPK8-626] Fix WaitOnJob when a job is retried

modules/database/funcs.go
To support multi cell deployment we need to support multiple DB service instances as in a realistic multi cell deployment each Nova cell needs its own DB service instance.
So this patch introduces CreateOrPatchDBWithLabel to the database module where the caller can specify a label selector map to filter for a specific MariaDB service instance to use for its DB schema. The existing and heavily used CreateOrPatchDB is defaulted to use the "default" DB service instance but deprecated for removal after each service controller starts using  CreateOrPatchDBWithLabel instead.
=> Support multiple DB service instance

modules/common/configmap/configmap.go
Whenever an operator creates a new `ConfigMap` using methods `createOrPatchConfigMap` or `createOrGetCustomConfigMap` the calculated has will not be correct.
Due to this incorrect hash we end up seeing 1 unnecessary destroy/create cycle of the pods.
In the Cinder where this was observed we would see that at least the cinder-volume, cinder-backup, and cinder-scheduler containers would successfully run their init containers and then the services would start running displaying their logs, but a couple of seconds later they would just be terminated just to do the cycle again.
After 1 terminate/create cycle they would stabilize.
We could see that their respective `StatefulSet` had a `generation` count of 2 (when it should be 1) and this was caused by a change of the `ConfigMap` hash.
The …
=> Fix hashing of ConfigMaps

modules/common/condition/conditions.go, modules/openstack/role.go, modules/openstack/service.go, modules/openstack/user.go
* Introduce <Type>NotFound error const
Adds ServiceNotFound, RoleNotFound and UserNotFound const, which allows to check for the specific error message and prevents hard coding specific error messages in different places.
* Validate in AssignUserRole() if the user is already part of role
Before assigning the user to a role, check if it is already part of it. In this case no update to the role assignment is required.
* Check service is already present in CreateService()
When the service with Name and Type is already present in keystone there is no need to create it. In this case just use it.
Also adds a new condition `KeystoneEndpointReadyCondition` and rewords the `ReadyInitMessage` and `ReadyMessage` to be more generic as it is not always a service which gets configured.
=> Improvements to openstack module

modules/database/funcs.go, modules/database/types.go
[database]Use databaseName for MariaDBDatabase Name
The CreateOrPatchDB() call used the caller's Name as the Name of the
MariaDBDatabase CR it created. But then later it tried to look it up by
using the Database.databaseName. When the two differs the CreateOrPatchDB
fails to create the DB.
Closes https://github.com/openstack-k8s-operators/lib-common/issues/65
Depends-on https://github.com/openstack-k8s-operators/lib-common/issues/67
=> Use Database.databaseName consistently to fix issue #65 

modules/database/funcs.go, modules/database/types.go
Deriving the database namespace from the before object doesn't work when that object has no namespace (such as for a Cluster scoped operator).
This change adds a variant of NewDatabase which allows a custom name and namespace.
=> Add NewDatabaseWithNamespace

modules/common/deployment/deployment.go, modules/common/deployment/types.go, modules/common/job/job.go, modules/common/job/types.go, modules/database/funcs.go
The overall goal is to make timeouts precisely configurable so that in envtest where DB, Job and Deployment creation success is simulated the test execution can be speeded up by setting a sub-second RequeueAfter value.
To achieve this:
* WaitForDBCreatedWithTimeout is introduced to take a timeout value in time.Duration instead of using a hard coded 5secs.
* Deployment and Job is changed to store time.Duration instead of seconds internally and a SetTimeout funcs are introduced to make that configurable
=> Make requeue timeouts more configurable

modules/database/funcs.go
Creating or updating a MariaDBDatabase should not be reported as error as it is not really an error condition. The controller just need to requeue the reconcilation to wait for the MariaDBDatabase reconciliation but should not log an error with a stack trace.
=> Do not log error for DB creation

modules/common/util/template_util.go, modules/common/util/template_util_test.go, modules/common/util/testdata/templates/common/common.sh, modules/common/util/testdata/templates/testservice/bin/1.0/init.sh, modules/common/util/testdata/templates/testservice/config/config.json, modules/common/util/testdata/templates/testservice/config/foo.conf
When there are multiple sub dirs to be removed from the templatedFiles list, the index no longer matches when the first one got removed. The removal loop should start from beginning when an entry got removed.
Also adds unit tests for the template util and comments to make it easier to understand the templating.
Depends-On: https://github.com/openstack-k8s-operators/lib-common/pull/70
=> Fix subdir removal from GetAllTemplates(), add unit tests and comments

modules/test/crd.go, modules/test/crd_test.go
We moved the CRD definitions of keystone and mariadb to the "bases" directory  of the api package. Adapt the CRD test utils to that change.
=> [test]Fix CRD utils after CRDs moved to API package

modules/common/endpoint/endpoint.go
Keystone endpoint points to the `Route` created on top of the specific `Service`, which is exposed on `data.Port`.
However, having the port in the `endpoint url` let the openstack cli fail because it tries to reach the `Route` on the port specified in the url.
This change just removes the port from the generated keystone endpoint.
Signed-off-by: Francesco Pantano <fpantano@redhat.com>
=> Do not include data.Port in the keystone endpoint

modules/common/job/job.go, modules/common/job/types.go
Currently lib-common automatically and immediately deletes the Job after it finished if preserve is set to false. However
* if the caller of DoJob fails to persist the fact that the Job is done (e.g. due to conflict) OR
* the caller's next reconcile reads stale data from cache seeing that the Job is not finished but also does not exists as it was already deleted
then the client has no way to decide that the Job does not need to be run again. This could lead to duplicate Job execution.
So this patch delays the automatic Job deletion with a default TTL of 10 minutes counted from the finish of the Job. We believe that this is plenty of time to allow the caller to successfully persist the Job state even if it has to retry it and to let the operator-sdk update the cache.
See the previous [fix …
=> Default TTLSecondsAfterFinished on Jobs

modules/common/statefulset/statefulset.go, modules/common/statefulset/types.go
Make the RequeueAfter timeout value configurable so that in an envtest environment it can be set to a lower than 1 second value to speed up the testing.
=> [StatefulSet]Allow fine grained RequeueAfter value

modules/test/helpers/common.go
Add getTestTimeout() that returns test timeout from TEST_TIMEOUT_SEC environment variable, in seconds. Or picks defaultTimeout, in milliseconds.
Make SkipInExistingCluster() callable via TestHelper to simplify lib-common/test/helpers imports.
Signed-off-by: Bogdan Dobrelya <bogdando@yahoo.com>
=> Wire-in TEST_TIMEOUT_SEC for testenv

modules/common/service/service.go, modules/common/service/types.go
StatefulSets require a headless service to manage the network identity of the pods[1]. A headless service itself is defined by specifying "None" as clusterIP[2].
[1] k8s.io/docs/concepts/workloads/controllers/statefulset/#limitations [2] k8s.io/docs/concepts/services-networking/service/#headless-services
=> Add clusterIP to Service

modules/common/statefulset/statefulset.go
ServiceName is required if a Service should govern a StatefulSet.
=> Add missing ServiceName to StatefulSet

modules/common/statefulset/statefulset.go
StatefulSet.CreateOrPatch did not support providing all the fields of appsv1.StatefulSet. Now it does. But we need to check back time to time and add any new fields of appsv1.StatefulSet to the mutateFn logic to expose them to our operators.
=> Allow setting fields on StatefulSet

modules/common/service/service.go
This change fixes one bad formatting detected by `go fmt`.
=> Fix minor format according to go fmt

modules/common/helper/helper.go
Intended to be used with our deferred-instance-patch-at-end-of-reconcile pattern
=> Generic instance update func

modules/common/annotations/network.go, modules/common/annotations/network_test.go
To attach additional interfaces via multus to resources the `k8s.v1.cni.cncf.io/networks` annotation needs to be added to the pod spec. e.g.
k8s.v1.cni.cncf.io/networks: '[{"name": "internalapi", "namespace": "openstack"},{"name": "storage", "namespace": "openstack"}]'
GetNADAnnotation() returns this annotation based on the namespace and the list of network-attachment-definitions passed in.
=> Add annotations package with GetNADAnnotation

modules/common/cronjob/cronjob.go, modules/common/cronjob/types.go
This introduces the basic implementation to manage CronJob resource type, so that individual operators can use this framework to set up house-keeping cron jobs such as db purge.
=> Add basic framework for CronJob resource type

modules/common/configmap/configmap.go, modules/common/cronjob/cronjob.go, modules/common/deployment/deployment.go, modules/common/job/job.go, modules/common/pvc/pvc.go, modules/common/pvc/types.go, modules/common/route/route.go, modules/common/route/types.go, modules/common/secret/secret.go, modules/common/service/service.go, modules/common/service/types.go, modules/common/statefulset/statefulset.go
instead of int. This allows us to use more fine grained timeout value such as 0.1, and encodes the unit in the type itself.
=> Use time.Duration for timeout

modules/common/util/template_util.go
We were mistakenly concating the `template` path with the `filename` before passing it to `path.Join()`, which resulted in errors like so (discovered by running MariaDB operator locally via `OPERATOR_TEMPLATES=./templates make run`):
```
"error": "open templatesdatabase.sh: no such file or directory"
```
Instead the `template` and `filename` args should be passed as separate items.
=> Fix util pkg use of path.Join()

modules/common/annotations/network.go, modules/common/condition/conditions.go, modules/common/endpoint/endpoint.go, modules/common/go.mod, modules/common/go.sum, modules/common/networkattachment/networkattachment.go, modules/common/networkattachment/networkattachment_test.go, modules/common/service/service.go, modules/common/service/types.go
Adds a MetalLBService type to create its LoadBalancer service. Also extends the endpoint Data with MetalLBData with the required input to create the MetalLB service.
=> Add MetalLB service type

modules/common/util/template_util.go, modules/common/util/template_util_test.go
Currently it does not work (probably since migrating these to common-lib modules). GetTemplatesPath() function signature has been changed. Looks like it's not called externally yet, hence there would be no impact.
=> Fix local testing without $OPERATOR_TEMPLATES

modules/common/condition/funcs.go, modules/common/condition/funcs_test.go
This is a breaking change on Conditions.Mirror(). Originally this call ordered conditions as False, True, Unknown then picked the first of that list to reflect. However all the use cases (we see) assume that if there is reasourceA that depends on the status of resourceB then resourceA reconciler calls:
```golang
resourceB.Status.Conditions.Mirror(ResourceBSpecificSubConditionOfA)
```
and expects that the call returns the most sever non True condition if any or return a True condition otherwise. So the original behavior that returned True even if there was Unknown condition was unexpected.
This patch changes the order of the status to False, Unknown, True. But keeps the original logic that if the ReadyCondition is True then the rest of the conditions are ignored even if there are False …
=> Mirror order conditions as False, Unknown, True

modules/common/condition/conditions.go
The previous attempt added only status names and the condition name is still missing. This fixes that.
Also, this replaces 'Cronjob' by 'CronJob' to make it consistent with the class name.
=> Add conditions for cronjobs (again)

Makefile, modules/storage/ceph/types.go
Having a CRD field with omitempty tag with a kubebuilder default value defined can cause unexpected behavior. See https://github.com/gibizer/operator-lint/blob/main/linters/crd/C003 for details.
So this patch remove the problematic definitions and bumps the operator-lint version to 0.3.0 that has a check to cover this.
=> Fix omitempty + default value

modules/common/condition/conditions.go
AnsibleEE objects will be called all around the place. It is useful to have conditions to check on their status from other services.
=> Added AnsibleEEReady condition

modules/common/route/route.go, modules/common/route/types.go
this change adds support for setting the Host
field on a route object form the autogenerated value
on update.  When a route is created for the first time
the Host value was previously populated with the autogenerated
vlaue but that did not happen during update.
now we copy the autogenerated value from the status if
the Host field is not set and we have an ingress values
in the status.
This change also adds an optional FQDN field to the route
to allow use to not use the autogeneration in the future
if we want too. Currently this is unused.
=> support autogenerated route host

Makefile
Previous implementation used external loop to control workspace inclusion. The builtin `-r` argument performs the same function.
=> Simplify golang workspace target

modules/common/condition/conditions.go
This patch fixes the message of DBReadyErrorMessage constant as it was referring to DBsync job but it is used for DB creation conditions.
While at it I fixed typos in the messages and discrepancies in the comments as well.
=> Fix condition messages

modules/common/const.go
This introduces a constant which defines the name of customized policy file. The file will be created as /etc/<service>/policy.d/custom.yaml in each service.
=> Add constant for policy customization

modules/common/endpoint/endpoint.go
This adds `Protocol` to the MetalLBData type to specify which one to use for the service. Defaults to TCP if non is specified.
=> Allow setting protocol used for metallb LoadBalancer service

modules/common/condition/conditions.go, modules/common/rbac/rbac.go
This function will act as the primary means to help reconcile common rbac resources for serviceaccounts, roles, and rolebindings.
Individual operators can define functions for the rbac.Reconciler interface within their CRD reconcilers and then make a simple call to reconcile all these resources in the controller like:
rbacRules := []rbacv1.PolicyRule{
{
APIGroups: []string{""},
Resources: []string{"pods"},
Verbs:     []string{"get", "list", "watch"},
},
}
rbacResult, err := common_rbac.ReconcileRbac(ctx, h, instance, rbacRules)
if err != nil {
return rbacResult, err
} else if (rbacResult != ctrl.Result{}) {
return rbacResult, nil
}
=> Add ReconcileRbac function

modules/common/go.sum, modules/common/util/template_util.go, modules/common/util/template_util_test.go, modules/common/util/testdata/templates/common/common.sh, modules/database/go.sum, modules/openstack/go.sum, modules/storage/go.sum, modules/test/go.sum
Currently in case a template parameter is missing, render does not fail immediately and the parameter is replaced by '<no value>' string. This makes it difficult to catch some problems like typos in parameter keys.
This makes the template rendering immediately fail in case any of the parameters are missing.
=> Abort if template parameter is missing

.github/workflows/golangci-lint.yaml, .golangci.yaml, .pre-commit-config.yaml, modules/common/annotations/network_test.go, modules/common/helper/helper_test.go, modules/common/networkattachment/networkattachment_test.go, modules/common/util/funcs_test.go, modules/common/util/hash_test.go, modules/common/util/template_util_test.go, modules/storage/ceph/util_test.go, modules/test/go.mod, modules/test/go.sum, modules/test/helpers/database.go, modules/test/helpers/keystone.go
Added golangci-lint execution in pre-commit and updated enabled linters. Fixed the ginkgolinter findings.
Also added a github action to run pre-commit. Eventually we want to run prow CI on lib-common but that needs more prep work.
=> Update pre-commit and golangci-lint setting

modules/test-operators/helpers/keystone.go
The nova-operator only depends on the public endpoint of Keystone so the original helper copied from nova-operator only simulates that one. However other operators like neutron-operator depends on the internal endpoint too. The keystone-operator by default creates both so the test helper also modified to simulate both.
```
$ oc get KeystoneAPI/keystone -o yaml | yq ".status.apiEndpoint"
{
"internal": "http://keystone-internal.openstack.svc:5000",
"public": "http://keystone-public-openstack.apps-crc.testing"
}
```
=> [test-operators]Simulate internal endpoint for Keystone

Makefile, modules/archive/go.mod, modules/archive/go.sum, modules/common/go.mod, modules/common/go.sum, modules/common/test/functional/job_test.go, modules/common/test/functional/suite_test.go, modules/database/go.mod, modules/database/go.sum, modules/openstack/go.mod, modules/openstack/go.sum, modules/test/helpers/common.go, modules/test/helpers/instance.go, modules/test/helpers/job.go
These tests uses envtest for the external dependencies
There are possible alternatives for this:
* golang unit test with a handrolled mock for the external dependencies
see https://github.com/openstack-k8s-operators/lib-common/pull/246
* controllerutils fake client (DEPRECATED) https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/client/fake
* k8s fake client https://pkg.go.dev/k8s.io/client-go/kubernetes/fake
(I'm not sure if it can be make compatible with controller-runtime)
* using mock libs / generators
Depends-on: https://github.com/openstack-k8s-operators/lib-common/pull/252
=> Job test with envtest

.github/workflows/golangci-lint.yaml
We run all pre-commit on both push to branch and open pull request events. This means that we run it also against master after a PR is approved. In that case the no-commit-to-branch check, that enforces no direct commit to master branch fails, so we disable this check in CI. Locally it still make sense to keep it as it is good git hygiene to always work on a local topic branch.
=> [pre-commit]skip branch check in CI

modules/common/job/job.go, modules/common/job/types.go, modules/common/test/functional/job_test.go
The job handling logic is changed to allow re-running the job if the
hash of the job changed while the previous job is still exists.
If the old job still not finished when DoJob is called with a new job
then the caller is requested to wait by returning requeue result
until the old job is finished (either succeeded or failed).
If the old job already finished when DoJob is called with a new job
then then the old job is deleted and the caller is requested to requeue.
So that when DoJob is called after this requeue the normal code path can
be taken, and a new job can be created as no job exists.
To be able to detect the if the hash of the job is changed while the old
job is still running the hash of the job is stored as an annotation on
the k8s job object. This way DoJob can compare the hash …
=> [Job]Support re-running the job while previous job still exists

modules/common/condition/conditions.go
This reason will be used by the dataplane-operator to signal that the
deployment has not yet been requested.
Signed-off-by: James Slagle <jslagle@redhat.com>
=> Add NotRequested condition Reason

modules/openstack/volume.go
Adds volume module with functions to manage
- ServiceCheck
E.g. Check whether particular cinder service is running or not.
=> Add volume module

modules/test/helpers/deployment.go, modules/test/helpers/job.go
We have couple of envtest helpers which call Update on existing k8s resources, for example to simulate a status condition. These updates can race with updates from the controller under test. In such case k8s will return 409. So this can cause random test instability. To avoid this this PR moves all Update calls into an Eventually block so the test will re-query the resource, reapply the change and redo the Update in a limited retry loop.
The only exception is CreateKeystoneAPI. That call creates an KeystoneAPI resource and updates its Status in a second Update call as the Status cannot be set during create as it needs a different client. In this case we don't expect anybody else to touch the KeystoneAPI resource.
=> [test]Use Eventually for all k8s Update calls

modules/test-operators/go.mod, modules/test-operators/go.sum, modules/test-operators/helpers/database.go, modules/test-operators/helpers/keystone.go, modules/test-operators/helpers/transport.go, modules/test/go.mod, modules/test/go.sum, modules/test/helpers/common.go, modules/test/helpers/conditions.go, modules/test/helpers/configmap.go, modules/test/helpers/deployment.go, modules/test/helpers/instance.go, modules/test/helpers/job.go, modules/test/helpers/namespace.go, modules/test/helpers/networkattachmentdefinition.go, modules/test/helpers/rbac.go, modules/test/helpers/route.go, modules/test/helpers/secret.go, modules/test/helpers/service.go, modules/test/helpers/statefulset.go
With this changes documentation of all test helpers will be visible here: https://pkg.go.dev/github.com/openstack-k8s-operators/lib-common/modules/test@v0.0.0-20230510145530-3c8e9179fb6e/helpers
=> Add documentation for test helpers functions

modules/common/service/service.go, modules/common/service/types.go
Some config options require special format according to the IP version used by a service. For example memcache server list used by python-memcached requires inet6 prefix in case memcached listens at an IPv6 address.
This change introduces the interface to obtain spec.IPFamilies of Service resource so that we can determine which IP version is used by a service.
=> Service: Add interface to obtain IPFamilies

modules/common/condition/conditions.go
This condition is not really used, because we only check whether the resource is created.
=> Remove unused CronJobReadyRunningMessage

modules/test/helpers/deployment.go, modules/test/helpers/statefulset.go
The helper simulating Pods for StatefulSets and Deployments are changed to support PVCs. Before this patch if PVC was present the Pod creation failed with missing volumes. Now the helper simply drops the volumes and mounts from the Pod it creates. Later on if we need a better solution we can translate PVCs from to volumes when creating the Pod, but I believe we will not need this in our tests.
=> [test]Handle PVC in StatefulSet and Deployment

modules/openstack/openstack.go
The `NewOpenStack` function is only used by `keystone` to get a an admin, system wide token that can be used by other operators through keystone service to register the associated resources. However, without `scope:system` `Glance` is not able to register the global limits defined in its main CR and it will fail configuring limits [1].
This patch ensures we have a system wide admin client that is able to act globally against the existing ctlplane.
[1] https://docs.openstack.org/glance/latest/admin/quotas.html#configuring-glance-for-per-tenant-quotas
=> Get gophercloud system wide client

modules/test/helpers/deployment.go, modules/test/helpers/statefulset.go
In #277 it was wrongly assumed that a StatefulSet of Deployment only has a single container spec and the volume mounts only removed from the first container. This leads to test failures in module using multiple containers per Pod.
Now this is fixed by dropping the mounts from each container.
=> [test]Fix PVC handling in SimulateDeployment

modules/test-operators/apis/common.go, modules/test-operators/apis/keystone.go, modules/test-operators/apis/server.go, modules/test-operators/go.mod, modules/test-operators/go.sum, modules/test-operators/helpers/keystone.go
The new KeystoneAPIFixture is able to simulate user and domain creation in OpenStack Keystone API by starting a local http server and responding to the API requests. Also the fixture allows registering test specific handlers to inject failure responses.
To utilize the fixture a new CreateKeystoneAPIWithFixture helper is added.
Example usage:
```golang
f := NewKeystoneAPIFixtureWithServer(logger)
f.Setup()
DeferCleanup(f.Cleanup)
name := th.CreateKeystoneAPIWithFixture(namespace, f)
DeferCleanup(th.DeleteKeystoneAPI, name)
```
=> Add KeystoneAPI simulator

modules/test-operators/helpers/memcached.go
This introduces a few helper functions to manage Memcached instance in envtest.
=> Add test helpers for Memcached instance

modules/test-operators/helpers/memcached.go
This fixes the value is incorrectly generated.
=> Memcached helper: Fix ServerListWithInet value

modules/common/condition/conditions.go
Now we define individual ready conditions and messages for Memcached and TransportURL but this is redundant because these implementations are almost same. This adds these into the lib-common module so that we can reuse the same definition.
=> Add common ready conditions/messages for Memcached/TransportURL

modules/common/test/helpers/configmap.go, modules/common/test/helpers/deployment.go, modules/common/test/helpers/job.go, modules/common/test/helpers/rbac.go, modules/common/test/helpers/route.go, modules/common/test/helpers/secret.go, modules/common/test/helpers/service.go, modules/common/test/helpers/statefulset.go, modules/test/helpers/database.go, modules/test/helpers/keystone.go, modules/test/helpers/transport.go
There are some cases where we want to ensure a resource is not yet created by the operator (eg. No resources should be created in case the global secret does not exist). This adds the helper functions to assert that.
This also removes the unused AssertConfigMapExists. This function can be replaced by GetConfigMap.
=> Add helpers to assert a resource does not exist

modules/openstack/project.go, modules/openstack/user.go
Keystone supports "domain" and users, groups and projects belong to a specific domain, and it's possible that multiple entries with the same name exist in different domains.
This introduces the interface to specify the domain where the user or the project should exist, to avoid unexpected behavior caused by such "duplicate" entities.
=> Give specific domain id for user/project

modules/database/funcs.go
We don't have to update a CR when the CR does not contain the finalizer being removed. This also removes some unused/redundant function from the Reconciler struct.
=> Skip redundant update when removing a finalizer

modules/certmanager/go.mod
On the main branch we want to continue tracking the main branch of our operator dependencies.
=> Unpin deps after dev-preview

modules/common/test/helpers/secret.go
This is pulled out from nova-operator as it is generic enough to be reused in other repos like in placement-operator
=> [envtest]Add UpdateSecret helper

modules/certmanager/certificate.go, modules/certmanager/issuer.go, modules/common/configmap/configmap.go, modules/common/route/route.go, modules/common/secret/secret.go, modules/common/service/service.go
Identified in OCP4.13 where metallb adds an annotation to the service when handling it, it resulted in reconcile loop since the current service CreateOrPatch did not expect that annotations will be altered outside the owner.
This changes the different functions to merge Labels and Annotations in CreateOr Patch instead of assigning.
=> Merge Annotations and Labels in CreateOrPatch

modules/certmanager/certificate.go, modules/certmanager/go.mod, modules/common/endpoint/endpoint.go, modules/common/route/route.go, modules/common/test/functional/route_test.go
* updates NewRoute() to support a list of overrides. Later overrides from the list will override parameters from previous. This allows to patch  custom provided overrides with the one for the TLS public endpoint by the openstack-operator.
* Adds EnsureCert() to request a certificate from an issuer and returns the a ptr to the secret holding the cert.
Jira: [OSP-26299](https://issues.redhat.com//browse/OSP-26299)
=> Allow route overrides list in NewRoute() and add EnsureCert()

modules/common/probes/probes.go, modules/common/probes/probes_test.go
Introduce a new package to handle liveness and readiness probes. Allow user configuration for port and toggle between HTTP/HTTPS.
=> General HTTP/HTTPS probes support

modules/common/tls/tls.go, modules/common/tls/tls_test.go
The service operators will have TLS struct type to pass in the reference to the certificates secrets as well as the option to add multiple CA certs.
Jira: [OSP-26846](https://issues.redhat.com/browse/OSP-26846)
=> Add the TLS struct support for service operators

modules/common/test/helpers/secret.go
These secrets are used in a considerable number of tests. Implementing separate function for generating them in each repo is suboptimal.
At this point this would see use in the dataplane-operator repo, but I expect that in the future a similar fixture would be useful for tests of other operators that have to use ssh connections.
=> Addin specialized utility function for genereting mock ssh secrets

modules/certmanager/certificate.go
This allows to pass in annotations and labels to be set on the created secret holding the certificates
Jira: OSP-26299
=> [TLS] add SecretTemplate via EnsureCert

Makefile
The `test` target in makefile doesn't run automated tests if a ginkgo test suite is provided by a module. Fix the target to always run all the tests provided by a module.
=> tests: enable both ginkgo and automated tests

modules/common/job/job.go
Simple change, so we don't ask the same question twice. 
The logging adjustment is intended to somewhat improve our situation if there is problem with job retrieval.
=> Removed duplicated conditional and improved logging message

modules/common/tls/tls.go, modules/common/tls/tls_test.go
New function to generate the mysql flags read by oslo.db to connect to a mysql database via TLS.
This commit also returns a fqdn for the database hostname, as it is required to validate the mysql database's certificate.
=> Helper function for TLS support in database access

modules/common/configmap/configmap.go, modules/common/secret/secret.go
Template parameter expansion has only been supported in template files themselves, and not in any other sources supplied in the customData. This patch extends support for expanding parameters in all customData strings.
The intent is to support template parameters in customServiceConfig data. A common use case is when a service's config parameter needs to be set to a value that can be templated, e.g. the service's own password.
Consider the glance service when it's configured to use cinder for a backend. The final configuration needs to specify the 'cinder_store_password', which currently requires two things.
1. The cloud admin will need to create a secret containing the setting, and reference it in the customServiceConfigSecrets.
2. The cloud admin will need to track down the actual value …
=> Support template parameters in configmap/secret customData

modules/certmanager/certificate.go, modules/certmanager/issuer.go
commonName has a max length of 64 chars, which easy can be reached in route DNS names scheme.
From [1]
~~~
RFC 2818, published in May 2000, deprecates the use of the Common Name (CN) field in HTTPS
certificates for subject name verification. Instead, it recommends using the
“Subject Alternative Name” extension (SAN) of the “dns name” type.
~~~
Lets not set the commonName an just use the subjectAltNames for our certs.
[1] https://cloud.redhat.com/blog/details-on-https-common-name-deprecation-in-openshift-4.10
=> [TLS] Don't set commonName and only use subjectAltNames

modules/common/condition/conditions.go
Indicating the condition when required TLS sources are ready.
=> Add TLSInputReadyCondition

Makefile
Minimal formatting change was introduced in the Makefile.
=> Restoring PROC_CMD var and normalizing test commands

modules/common/go.mod, modules/common/go.sum, modules/common/object/metadata.go, modules/common/object/metadata_test.go, modules/common/test/functional/object_test.go
Adds object package to the common module with initial functions to add additional non controller owner references to objects. This allows additional owners to watch resources
```
// watch for secrets we added ourselves as additional owners, NOT as controller
Watches(
&source.Kind{Type: &corev1.Secret{}},
&handler.EnqueueRequestForOwner{OwnerType: &clientv1.OpenStackClient{}, IsController: false}).
```
Note: Adding as an additional owner will not triggere a reconciliation when the object gets re-created from scratch, like deleting a secret.
=> Add object package with generic ownerref func

modules/test/crd.go, modules/test/crd_test.go
Ginkgo test suites require fetching the CRDs of the custom resources used in the tests. Those are fetched from the go.mod and any replace statement is parsed and honoured.
Add the ability to process replace statements that point to a local directory as well, to ease the developement process when a project depends on a feature from another project that has not been merged yet.
=> test: allow fetching CRD from a local replace statement

modules/certmanager/certificate.go, modules/certmanager/go.mod, modules/certmanager/go.sum, modules/certmanager/test/functional/certmanager_test.go, modules/certmanager/test/functional/suite_test.go, modules/common/test/helpers/service.go
Adds function EnsureCertForServicesWithSelector() to create certs for a k8s services identified by a label selector and EnsureCertForServicesWithSelector() where the expectation is that the selector maps to a single service.
=> [certmanager] Add EnsureCertForServicesWithSelector() and EnsureCertForServiceWithSelector()

modules/common/route/route.go, modules/common/service/service.go
with 18d0ea2c06a85f0d9a329c8f7ffbff41afeb0f1c we introduced merging annotations and labels. It was required as other components can add annotations to a created service:
~~~
Author: Martin Schuppert <mschuppert@redhat.com>
Date:   Wed Sep 27 09:06:26 2023 +0200
Merge Annotations and Labels in CreateOrPatch
Identified in OCP4.13 where metallb adds an annotation to the
service when handling it, it resulted in reconcile loop since
the current service CreateOrPatch did not expect that annotations
will be altered outside the owner.
This changes the different functions to merge Labels and Annotations
in CreateOr Patch instead of assigning.
~~~
With the current order of how the labels on routes and services get created does not allow to change a value of an existing key as how the merge func …
=> [service/route] allow updating labels and services

renovate.json
Both openstack and certmanager module depends on the common module within the same repo and both go.mod files has a replace line to use the in repo version of that dependency. Therefore it is not necessary to bump the pseudoversion of the common module in those go.mod files. So this PR disables those renovate bumps to avoid unnecessary CI churn.
=> [renovate]Do not bump common module within lib-common

modules/common/route/route.go, modules/common/route/route_test.go
I think this might need testing, but looking at similar PR (https://github.com/openstack-k8s-operators/lib-common/pull/418) I did not fully understand how I should create something similar to what we see there in "modules/common/service/service_test.go" for the Route struct.
=> Add AddLabel()/AddAnnotation() for Route

modules/common/cronjob/cronjob.go
Until now the update on the CronJob Spec fields was ignored. So
for example Schedule could not be upgraded.
This is fixed know.
=> [CronJob]Support updating config

modules/common/test/helpers/instance.go
When the helper deletes a resource it checks that it is not found any
more (i.e.:finalizeres are not blocking the deletion). But it checks by
resource name so if the resource is recreated in the meantime with the
same name then the helper will think the deletion did not happened.
This patch makes sure that only the original resource is deleted by
checking its UID.
=> Fix DeleteInstance helper to check UID

modules/common/service/types.go
In telemetry-operator, we use the cluster-observability-operator to manage prometheus. COO creates a prometheus service with a target port name "web", which is different from the name of the service. COO doesn't create routes. This annotation lets us specify the intended target port name and use the openstack-operator to create a route for us after adding this annotation to the COO created service.
=> Add annotation for specifying ingress target port.

modules/common/const.go
The service and job Debug feature is removed from the operators in favor of using oc debug directly.
Implements: [OSPRH-4290](https://issues.redhat.com/browse/OSPRH-4290)
=> Drop DebugCommand const

modules/common/go.mod, modules/common/ocp/ocp.go
For FIPS support we need to be able to tell when an OCP cluster has been deployed in FIPS mode (it's a day one operation).
This patch adds the `IsFipsCluster` function that checks if FIPS is enabled or not.
The way to do that is checking the install-config YAML that is stored in the cluster-config-v1 Config Map.
If we find the fips key, and it has the true value, then it's deployed in FIPS mode, otherwise it isn't.
Related patch: https://github.com/openstack-k8s-operators/openstack-operator/pull/657
Jira: #OSPRH-4666
=> FIPS: Add common/ocp module

modules/common/condition/funcs.go, modules/common/condition/funcs_test.go
In order to consume `hasSameState` function in the service operators, we need to export this function from `common/condition` module.
This patch just turns it into an exported function that we can consume from the service operators.
=> Turn conditions.hasSameState function public

modules/common/condition/funcs.go, modules/common/condition/funcs_test.go
The RestoreLastTransitionTimes function facilitates preserving a condition's LastTransitionTime if a controller reinitializes its conditions at the start of every reconcilation. Controllers can use the following sequence in their reconciliation code:
- Save a copy of the current conditions
- Reinitialize conditions to Unknown
- Reconcile, which updates the conditions to their new state
- Call RestoreLastTransitionTimes
For conditions whose state doesn't change, the LastTransitionTime is set back to the time recorded in the saved copy. This prevents the LastTransitionTime from changing unless the condition itself actually changes state.
=> conditions: add RestoreLastTransitionTimes function

modules/common/test/helpers/deployment.go, modules/common/test/helpers/statefulset.go
In order to be able to rollout the full `.ObservedGeneration` pattern we need `envTests` to pass if this is added as a condition to mark a `Deployment` or `StatefulSet` `Ready`. 
This change introduces this parameter for the test module so we can take it into account in the envTests when the `DeploymentReadyCondition` is computed.
=> Add .ObservedGeneration to statefulset and deployments test module

modules/certmanager/certificate.go
Allow setting the subject of a certificate via the certrequest.
=> [certmanager] add subject and common name to certrequest

modules/common/service/types.go, modules/common/service/types_test.go
This method can e.g. be used in webhooks to validate if the configuration in the CR is correct.
=> Add service Endpoint Validate() method

modules/common/tls/tls.go, modules/common/util/map.go, modules/common/util/map_test.go
`AdditionalSubjectNames` represents the key to access a comma separated list of `additionalSubjectNames` that should be passed to the `CertificateRequest`.
=> Add AdditionalSubjectNames and the related function to tls module

modules/test/crd.go
Qualify of life improvement that skips path encoding on systems where it's likely to cause test failures - Macs, it impacts Macs.
Look, I appreciate that this is a selfish change and only impacts a small subset of engineers. But it's annoying to edit this file and get tests passing locally each time.
=> Skip encodePath based on runtime GOOS

modules/common/helper/helper.go
Per Custom Resource Definition docs [1], custom finalizer names are expected to be in format "consist of a domain name, a forward slash and the name of the finalizer" (e.g. foo.bar/name).
This aligns the finalizer provided by the helper to follow this definition and uses openstack.org/<gkv.kind> (all lower case) as the finalizer.
[1] https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#finalizers:~:text=Identifiers%20of%20custom%20finalizers%20consist%20of%20a%20domain%20name%2C%20a%20forward%20slash%20and%20the%20name%20of%20the%20finalizer
=> Align finalizer with Custom Resource Definition doc

modules/common/service/service.go, modules/common/test/functional/service_test.go
If there is an issue with the LoadBalancer service in the cluster, like the MetalLB instance is down, or the requested IP using the metallb.universe.tf/loadBalancerIPs annotation is outside the configured range of the IPAddressPool, the k8s LoadBalancert service External-IP is stuck in pending. This would not allow dataplane service to connect to the service.
This change returns an error in this case to reflect that there is an issue with the k8s service, which needs to be fixed and the consumer of the func can reconcile to wait for a LoadBalancer IP to be available.
=> [svc] return error if no LoadBalancer IP

modules/common/webhook/storage.go, modules/common/webhook/storage_test.go
Adds webhook package, intended to be a collection of webhook funcs, which can be used by the service operators.
This initial one will add a `ValidateStorageRequest()` func which validates a storage request meets a provided min size. Depending on the err (bool) parameter, the check result is either a warning or an invalid error.
=> Add webhook package, to be used for common webhook checks

modules/common/ocp/ocp.go, modules/common/test/helpers/ocp.go, modules/test/openshift_crds/config/v1/network_crd.yaml
The RabbitMQ config differs for IPv6 so add a function to determine if IPv6 is enabled on the OCP cluster network
Related: OSPRH-8372
=> Add function to check for OCP IPv6 cluster network

modules/common/ocp/ocp.go, modules/common/test/helpers/ocp.go, modules/test/openshift_crds/config/v1/network_crd.yaml
The RabbitMQ config differs for IPv6 so add a function to determine if IPv6 is enabled on the OCP cluster network
Related: OSPRH-8372
=> [18.0.0-proposed] Add function to check for OCP IPv6 cluster network

modules/common/webhook/rfc.go, modules/common/webhook/rfc_test.go
validates a list of strings are RFC 1123 label conform. Using the correction parameter the validation.DNS1123LabelMaxLength (63) get reduced by the provided int to be control the max lenght.
Related: OSPRH-8063
=> [webhook] add ValidateDNS1123Label webhook func

modules/certmanager/certificate.go, modules/certmanager/test/functional/certmanager_test.go
=> Requeue when TLS secret isn't found

modules/common/affinity/affinity.go, modules/common/affinity/affinity_test.go
The affinity weight ca be between 1 and 100 for each instance of the preferredDuringSchedulingIgnoredDuringExecution affinity type. When the scheduler finds nodes that meet all the other scheduling requirements of the Pod, the scheduler iterates through every preferred rule that the node satisfies and adds the value of the weight for that expression to a sum.
To make the pods better spread bump the weight to the max. Still the anti affinty is "this Pod should not run in an X if that X is already running one or more Pods that meet rule Y", which means if there are less nodes, but enough resources, the pods get scheduled there.
Related: https://issues.redhat.com/browse/OSPRH-8870
=> Change weight assigned to podAntiAffinity to 100

modules/common/affinity/affinity.go, modules/common/affinity/affinity_test.go
The affinity weight ca be between 1 and 100 for each instance of the preferredDuringSchedulingIgnoredDuringExecution affinity type. When the scheduler finds nodes that meet all the other scheduling requirements of the Pod, the scheduler iterates through every preferred rule that the node satisfies and adds the value of the weight for that expression to a sum.
To make the pods better spread bump the weight to the max. Still the anti affinty is "this Pod should not run in an X if that X is already running one or more Pods that meet rule Y", which means if there are less nodes, but enough resources, the pods get scheduled there.
Related: https://issues.redhat.com/browse/OSPRH-8870
(cherry picked from commit c61e7505bdcf5d3e209d14ed1188ad596efc6157)
=> [18.0.0-proposed]Change weight assigned to podAntiAffinity to 100

modules/common/configmap/configmap.go, modules/common/secret/secret.go
Returning a non-nil err with a RequeueAfter result causes k8s to discard the explicit requeue and wait much longer than desired.
=> Log 'not found' error instead of returning it alongside RequeueAfter

modules/certmanager/certificate.go, modules/certmanager/test/functional/certmanager_test.go, modules/common/net/ip.go, modules/common/net/ip_test.go
To reduce possibility of changing certs, make sure lists of DNSNames and IPAddresses are sorted.
=> [cert] Make sure DNSNames and IPAddresses are sorted

modules/common/condition/conditions.go
Given that we no longer return an error for k8s "not found" errors, we should add a message for TLSInput that can be used in `ctrlResult != ctrl.Result{}` situations (which indicate that a `Secret` is not found).
=> Add message for waiting for TLS input resources

modules/test/crd.go
There's a second function that encodes the path and needs to also check for the darwin runtime before doing it. This enables tests of operators that import openshift CRD's to run on MacOS platforms.
=> Fix for Mac

modules/common/service/types_test.go
ValidateRoutedOverrides does not guarantee a specific order of the returned ErrorList. As a result the "Multiple wrong override endpoints" sometimes fails even the expected errors are in the list. This changes to use ContainElements as it does not matter which order the errors are in the returned ErrorlList from ValidateRoutedOverrides.
=> Fix TestValidateRoutedOverrides

modules/common/test/functional/tls_test.go, modules/common/tls/tls.go
ValidateCertSecrets miss information on which cert secret is missing. Lets not return a crtlResult in case of a cert secret is missing, instead return a NotFound error and let the caller decide what to do.
Jira: OSPRH-9991
=> [tls] ValidateCertSecret to not return ctrlResult

modules/common/tls/tls.go
right now err.Error() renders as
~~~
secrets \"%s not found in namespace %s\" not found
~~~
This changes the msg so that it returns
~~~
secrets \"%s in namespace %s\" not found
~~~
Jira: OSPRH-9991
=> Fix ValidateCertSecret error message

modules/certmanager/certificate.go, modules/certmanager/test/functional/certmanager_test.go, modules/common/condition/conditions.go, modules/common/condition/funcs.go, modules/common/daemonset/daemonset.go, modules/common/net/ip.go, modules/common/net/ip_test.go, modules/common/service/types_test.go, modules/openstack/domain.go, modules/openstack/limits.go, modules/openstack/project.go, modules/openstack/role.go, modules/openstack/service.go, modules/openstack/user.go, modules/test/crd.go
backport of multiple fixes
* [[cert] Make sure DNSNames and IPAddresses are sorted](https://github.com/openstack-k8s-operators/lib-common/commit/8b38028103f174d3210cbdcf84d009d38078deaa) 
* [Add message for waiting for TLS input resources](https://github.com/openstack-k8s-operators/lib-common/commit/726023dd86be233fecbce82afdd1e8339d5023c9) 
* [Fix TestValidateRoutedOverrides](https://github.com/openstack-k8s-operators/lib-common/commit/4013011e7a8be3fc9128d21110efc6d4e28c5bed) 
* [Fix for Mac](https://github.com/openstack-k8s-operators/lib-common/commit/64efb3c77b45ca94c7fc280c3485498f22fb4b23) 
* [[daemonset] Make get method public](https://github.com/openstack-k8s-operators/lib-common/commit/7b4b5554bd838662de403474f73f6ee169151085) 
* [[govet] Fix printf: non-constant format string in …
=> [18.0.0-proposed] several back ports of fixes

.github/workflows/codeql.yml, README.md
Actions need to be updated, we can also drop the separate build action, as that is now rolled into the analyze action.
https://github.blog/changelog/2024-01-12-code-scanning-deprecation-of-codeql-action-v2/
=> Updating CodeQL workflow and adding a badge

modules/common/webhook/rfc.go, modules/common/webhook/rfc_test.go
validates a list of strings are RFC 1123 label conform. Using the correction parameter the validation.DNS1123LabelMaxLength (63) get reduced by the provided int to be control the max lenght.
Related: OSPRH-8063
Signed-off-by: Martin Schuppert <mschuppert@redhat.com>
(cherry picked from commit d524c2a3e1917dbc70a3b221a52f76fa6f000423)
=> [18.0.0-proposed] [webhook] add ValidateDNS1123Label webhook func

.github/workflows/codeql.yml
Yaml format error somehow passed the CI during recent changes to the codeql.
=> Fixing mapping error

modules/common/util/template_util.go, modules/common/util/template_util_test.go, modules/common/util/testdata/templates/testservice/config/bar.conf
Adds templat functions which:
- to exec an inline template
- indent a template
- remove n continuous empty lines from a template
An example would be a template like:
```
{{define "my-template"}}new template
content
with empty lines
to
remove
{{end}}
Some other template content and add the rendered from my-template
{{$var := execTempl "my-template" . | removeNewLines 1}}
{{$var}}
```
=> Add additional template functions

modules/common/condition/conditions.go
=> [condition] Add CreateServiceReadyCondition

modules/common/test/helpers/networkattachmentdefinition.go
Related: https://issues.redhat.com/browse/OSPRH-8680
=> [test helper] fix nad test helper to return valid json config

modules/common/networkattachment/networkattachment.go, modules/common/networkattachment/networkattachment_test.go
Adds function to return the result of the jsonPath as string from the NetworkAttachmentDefinition config. If the NAD has no config, an empty string is returned.
The jsonPath must be in the format e.g. ".ipam"
=> [nad] Add GetJsonPathFromConfig

modules/common/test/helpers/nad.go, modules/common/test/helpers/pod.go
GetNAD - retrieves a NetworkAttachmentDefinition resource.
Example usage:
```
th.GetNAD(types.NamespacedName{Name: "test-nad", Namespace: "test-namespace"})
```
CreateNAD creates a new NetworkAttachmentDefinition resource with the provided spec.
Example usage:
```    
spec := map[string]interface{}{"key": "value"}
p := th.CreateNAD(types.NamespacedName{Namespace: "default", Name: "example"}, spec)
```
CreatePod creates a new Pod resource with the provided annotations and spec.
Example usage:
```    
annotations := map[string]string{}{"key": "value"}
spec := map[string]interface{}{"key": "value"}
p := th.CreatePod(types.NamespacedName{Namespace: "default", Name: "example"}, annotations, spec)
```
=> [test] Add additional test helpers for pod and NAD

modules/common/condition/funcs.go, modules/common/condition/funcs_test.go
Recently the operators changed to use CreateServiceReadyCondition instead of ExposeServiceReadyCondition. An update of an existing environment would result in the ExposeServiceReadyCondition to be never removed from the conditions list of a CR because the list is not reset on Init().
This adds a Reset() method and a call right at the start of Init().
Related: https://issues.redhat.com//browse/OSPRH-4164
=> [conditions] Reset conditions on Init()

modules/common/util/template_util.go, modules/common/util/template_util_test.go
Right all templates are expected to be local files.
This change allows passing in optional templates via `StringTemplate` where the template is a full template string.
=> [template] Allow passing in a template string using StringTemplate

modules/common/const.go
Adds TemplateParameters const, which reflects the name of the key when storing a dump of the template parameters in the secret.
Jira: https://issues.redhat.com/browse/OSPRH-13100
=> [const] Adds TemplateParameters const

modules/common/labels/labels.go, modules/common/topology/topology.go
Replicate the defaulting behaviour used in cluster-level default constraints https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/#cluster-level-default-constraints
=> [topology] Add optional default for topologyConstraint LabelSelector

.golangci.yaml, modules/certmanager/certificate.go, modules/certmanager/issuer.go, modules/common/condition/conditions.go, modules/common/configmap/configmap.go, modules/common/job/job.go, modules/common/pod/pod.go, modules/common/probes/probes.go, modules/common/secret/secret.go, modules/common/service/service.go, modules/common/service/types.go, modules/common/service/types_test.go, modules/common/util/errors.go, modules/openstack/domain.go, modules/openstack/limits.go, modules/openstack/openstack.go, modules/openstack/project.go, modules/openstack/role.go, modules/openstack/service.go, modules/openstack/user.go, modules/storage/ceph/funcs.go, modules/test/crd.go
To follow best practices for error and exception handling in Go and to prevent regressions, err113 and gosec checks in golang-ci-linter are now enabled. Not all errors are corrected to not interfier to much with other repos.
=> Improve error handling

modules/common/service/types.go
In openstack-operator, where we bump all the sub components CRDs, we are currently getting an error thrown by crd-schema-checker:
```
ERROR: "ListsMustHaveSSATags": crd/openstackcontrolplanes.core.openstack.org version/v1beta1 field/^.spec.designate.template.designateUnbound.override.services[*].spec.loadBalancerSourceRanges must set x-kubernetes-list-type
ERROR: "ListsMustHaveSSATags": crd/openstackcontrolplanes.core.openstack.org version/v1beta1 field/^.spec.designate.template.designateMdns.override.services[*].spec.loadBalancerSourceRanges must set x-kubernetes-list-type
ERROR: "ListsMustHaveSSATags": crd/openstackcontrolplanes.core.openstack.org version/v1beta1 field/^.spec.designate.template.designateBackendbind9.override.services[*].spec.loadBalancerSourceRanges must set …
```
=> Fix ListsMustHaveSSATags raised by crd-schema-checker

modules/common/util/errors.go
Adding new general error messages that will be used in neutron and ovn operators.
These messages should be extendable to add detail as needed and be reused by other operator repos.
=> Adding new general errors messages

modules/common/labels/labels.go
This function is used as utility to get the list of `matchLabels` used as `selector` for `Deployments` and `StatefulSet`. Most of the service operators use to pass a `serviceLabels map[string]string`, which is available in the controller(s). This function translates the data structure into a `metav1.LabelSelector` that we can easily plug to the existing `ensureTopology` logic provided by infra-operator [1].
[1] https://github.com/openstack-k8s-operators/infra-operator/blob/main/apis/topology/v1beta1/topology_types.go#L126
=> Add GetLabelSelector utility function

modules/common/webhook/storage.go, modules/common/webhook/storage_test.go
In case of a wrong user input, the operator crashes without any chance to recover.
The `MustParse` implementation wraps the `ParseQuantity` function, that instead of `panic()` returns an error that can be easily handled at the operator level. This change does not alter the current behavior, but it adds a preliminary check that does not let the validation continue if the quantity is not valid. It also moves away from `MustParse` in favor of `ParseQuantity`. By doing this we can get a `webhook` feedback about the wrong quantity instead of checking the operators log and see the panic stacktrace.
This has been fixed in Glance and Swift [1][2].
[1] https://github.com/openstack-k8s-operators/glance-operator/pull/364
[2] https://github.com/openstack-k8s-operators/swift-operator/pull/190
=> Do not use MustParse with wrong StorageRequest size

modules/common/daemonset/daemonset.go
Currently on ovn-operators we may need to modify the updateStrategy for the daemonset, this is currently not supported, as if the updateStrategy is modified on the daemonset, this won't be reflected on the openshift cluster
Related: OSPRH-11636
=> Allow setting updateStrategy on DaemonSet

Makefile
fails with current released v2.0.0
=> [golangci] pin to v1.64.8

modules/common/deployment/deployment.go, modules/common/statefulset/statefulset.go, modules/common/test/helpers/deployment.go, modules/common/test/helpers/statefulset.go
Adds IsRead() for deployment and statefulset which can be used to validate when a deployment for the current Generation is fully provisioned and e.g. no rollout in progress.
Jira: OSPRH-14472
=> [deployment/statefulset] add IsReady func

modules/common/deployment/deployment.go, modules/common/statefulset/statefulset.go, modules/common/test/helpers/deployment.go, modules/common/test/helpers/statefulset.go
Adds IsRead() for deployment and statefulset which can be used to validate when a deployment for the current Generation is fully provisioned and e.g. no rollout in progress.
Jira: OSPRH-14472
=> [18.0-fr2][deployment/statefulset] add IsReady func

modules/openstack/openstack.go
It allows to use a Tenant from a different Domain than the User (see comment in gophercloud [0]).
Required by octavia-operator in [1]
[0] https://github.com/gophercloud/gophercloud/blob/849d9ea43b3c0659742ceea3fafb4f0f84b682ec/auth_options.go#L63-L66
[1] https://github.com/openstack-k8s-operators/octavia-operator/pull/478
JIRA: OSPRH-15809
=> Add TenantID in AuthOpts

modules/common/operator/options.go, modules/common/operator/options_test.go
Add operators package, implements function setOperatorOptions which takes a pointer to controller options parses env vars and set's options.
Jira: OSPRH-16335
=> Add operator package

modules/common/condition/conditions.go
Because we plan to consume notificationBusInstance parameters across the board, it might be a good idea to have common conditions in the shared module.
Jira: https://issues.redhat.com/browse/OSPRH-15845
=> Add NotificationBusInstance condition messages
